apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: lab2-services
data:
  env: "{{ .Values.env }}"
  MYSQL_HOST: "{{ .Values.mysql.host }}"
  MYSQL_PORT: "{{ .Values.mysql.port }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"