server:
  port: 8086
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: ase-file-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB