version: '3'
services:
  mysql-container:
    image: mysql:8.0.34
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 4iKqWz0dasVpC0z4EQUK
    volumes:
      - main-mysql-data:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    restart: always
volumes:
  main-mysql-data: