bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /conference/.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your Request Quota\" }"
      http-status-code: TOO_MANY_REQUESTS
      rate-limits:
        - cache-key: "getCookies().?[name == 'satoken'].length > 0 ? getCookies().?[name == 'satoken'][0].value : 'default'" # 使用SpEL获得请求中的token，作为限流的key。每一个token（用户）对应一个限流桶
          execute-condition: "true" # 限流条件，这里是无条件限流
          bandwidths:
            # bucket4j限流规则：令牌桶的容量为8，每秒钟充入3个令牌。采用GREEDY策略，即每1/3秒就会充入一个令牌，而不是等到1秒后一次性充入3个令牌
            - unit: seconds
              time: 1
              capacity: 8
              refill-speed: GREEDY
              refill-capacity: 3
spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=1d
  config:
    import: classpath:application-base.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql.lab2-middlewares.svc.cluster.local}:${MYSQL_PORT:3306}/ase_conference_service_prod
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:4iKqWz0dasVpC0z4EQUK}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: ase-conference-service
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 10
      # Redis服务器地址
      host: ${REDIS_HOST:redis.lab2-middlewares.svc.cluster.local}
      # Redis服务器连接端口
      port: ${REDIS_PORT:6379}
      # Redis服务器连接密码（默认为空）
      password: ${REDIS_PASSWORD:5iwrnpFC4BRqADn6qCFV}
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
dubbo:
  application:
    name: ase-conference-service
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    name: tri
    port: 20883
  registry:
    address: N/A
  consumer:
    timeout: 30000
    mesh-enable: true

