apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ase-contribute-des-rule
  namespace: ravusage
spec:
  host: ase-contribute-service.ravusage.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

