version: '3'
services:
  ase-dev-nginx:
    image: nginx:1.21.1-alpine
    container_name: ase-dev-nginx
    ports:
      - "8079:80"
    volumes:
      - ./ase_frontend/default.nginx.dev.conf:/etc/nginx/nginx.conf
