spring:
  config:
    import: classpath:application-base.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql.lab2-middlewares.svc.cluster.local}:${MYSQL_PORT:3306}/ase_user_service_prod
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:4iKqWz0dasVpC0z4EQUK}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: ase-user-service
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 10
      # Redis服务器地址
      host: ${REDIS_HOST:redis.lab2-middlewares.svc.cluster.local}
      # Redis服务器连接端口
      port: ${REDIS_PORT:6379}
      # Redis服务器连接密码（默认为空）
      password: ${REDIS_PASSWORD:5iwrnpFC4BRqADn6qCFV}
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
dubbo:
  application:
    name: ase-user-service
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    name: tri
    port: 20881
  registry:
    address: N/A
  consumer:
    timeout: 30000
    mesh-enable: true

